import {  getCurrentInstance } from 'vue';
import { createI18nTranslate } from '../../locale/create';

export function parseHTMLStringToDomList(html: string): NodeList | any[] {
  const domParser = new DOMParser();
  const htmlNode = domParser.parseFromString(html, 'text/html');
  return htmlNode.querySelector('body') ? htmlNode.querySelector('body')?.childNodes || [] : [];
}

const app = getCurrentInstance();
const t = createI18nTranslate('DEditorMd', app);
export function locale(key: string): string {
  const localeMap: Record<any, string> = {
    undo: t('undo'),
    redo: t('redo'),
    clean: t('clean'),
    header: t('header'),
    normal: t('normal'),
    h1: t('h1'),
    h2: t('h2'),
    h3: t('h3'),
    h4: t('h4'),
    h5: t('h5'),
    h6: t('h6'),
    font: t('font'),
    size: t('size'),
    songti: t('songti'),
    yahei: t('yahei'),
    kaiti: t('kaiti'),
    heiti: t('heiti'),
    lishu: t('lishu'),
    bold: t('bold'),
    italic: t('italic'),
    underline: t('underline'),
    strike: t('strike'),
    color: t('color'),
    backgound: t('backgound'),
    orderedlist: t('orderedList'),
    unorderedlist: t('unorderedList'),
    checklist: t('checkList'),
    left: t('left'),
    center: t('center'),
    right: t('right'),
    image: t('image'),
    file: t('file'),
    table: t('table'),
    link: t('link'),
    code: t('code'),
    codeblock: t('codeBlock'),
    blockquote: t('blockQuote'),
    superscript: t('superScript'),
    subscript: t('subScript'),
    globallink: t('globalLink'),
    emoji: t('emoji'),
    fullscreen: t('fullScreen'),
    'exit-fullscreen': t('exitFullScreen'),
    help: t('help'),
    more: t('more'),
    'help-format': t('helpFormat'),
    'help-insert': t('helpInsert'),
    'help-operation': t('helpOperation'),
    mention: t('mention'),
    'quick-menu': t('quickMenu'),
    'toggle-help-panel': t('toggleHelpPanel'),
    'scroll-table': t('scrollTable'),
    'mouse-wheel': t('mouseWheel'),
    save: t('save'),
    'copy-cells': t('copyCells'),
    'copy-table': t('copyTable'),
    'cut-cells': t('cutCells'),
    'empty-cells': t('emptyCells'),
    'insert-row-up': t('insertRowUp'),
    'insert-row-down': t('insertRowDown'),
    'insert-column-left': t('insertColumnLeft'),
    'insert-column-right': t('insertColumnRight'),
    'merge-cells': t('mergeCells'),
    'unmerge-cells': t('unmergeCells'),
    'delete-row': t('deleteRow'),
    'delete-column': t('deleteColumn'),
    'delete-table': t('deleteTable'),
    'default-link-text': t('defaultLinkText'),
    basicblock: t('basicBlock'),
    linkplaceholder: t('linkPlaceholder'),
    'counter-template': '{{count}}/{{totalCount}}',
    char: t('char'),
    word: t('word'),
    'counter-limit-tips': t('counterLimitTips'),
    'ie-msg': t('ieMsg'),
    loading: t('loading'),
    pasting: t('pasting')
  }
  return localeMap[key];
}