<template>
  <div class="demo-spacing">
    <d-button
      icon="add"
      variant="solid"
    >
      New
    </d-button>
    <d-button icon="filter">
      Filter
    </d-button>
    <d-button
      icon="connect"
      variant="text"
    >
      Link
    </d-button>
    <d-button
      icon="delete"
      variant="text"
      title="Delete"
    />
    <d-button
      shape="round"
      title="Add"
    >
      Add
    </d-button>
    <d-button
      icon="delete"
      shape="circle"
      title="Delete"
      size="sm"
    />
    <d-button
      icon="delete"
      shape="circle"
      title="Delete"
    />
    <d-button
      variant="solid"
      icon="filter"
      shape="circle"
      title="Add"
      size="lg"
    />
  </div>
</template>;
