name: 🐛 Bug Report
description: Something is wrong with Vue Devui.
title: "🐛 [Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!

        Do you need some help?
        ======================
        The issue tracker is meant for feature requests and bug reports only. This isn't the best place for
        support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before
        you ask a question, here are some resources to get help first:

        - Read the docs: https://vue-devui.github.io/
        - Ask in GitHub Discussions: https://github.com/DevCloudFE/vue-devui/discussions
        - Ask in WeChat: add this WeChat(devui-official), we will invite you to the WeChat discussion group later

  - type: checkboxes
    id: packages
    attributes:
      label: Which Vue Devui packages are impacted?
      options:
        - label: "`vue-devui` (Vue Devui core)"
        - label: "`devui-cli`"
  - type: input
    attributes:
      label: What version of Vue Devui are you using?
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Node are you using? Minimum supported version is 12.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: In what environment are you using Vue Devui?
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
